# Fig. 6 - class-associated residues on the GHSR structures
# generated by revision/make_fig6_pymol.py - distances match Table 1
reinitialize
bg_color white
set ray_opaque_background, 1
set orthoscopic, 1
set cartoon_fancy_helices, 1
set cartoon_transparency, 0.45
set stick_radius, 0.26
set sphere_scale, 0.30
set label_size, 16
set float_labels, 1
set label_connector, 1
set label_connector_color, grey50
set label_connector_width, 1.2
set label_connector_mode, 1
set label_color, black
set label_outline_color, white
set label_position, (0, 2.2, 0)
set dash_width, 2.2
set dash_gap, 0.35
set dash_color, grey40
set depth_cue, 0
set ray_shadows, 0
set antialias, 2

# ---------------- 8jsr: agonist-bound (anamorelin) ----------------
# expects 8jsr.pdb beside this script, otherwise use:
#   fetch 8JSR, 8jsr, async=0
load 8jsr.pdb, 8jsr
remove 8jsr and not (chain R or resn UYI)
# chain R of 6KO5 also carries a BRIL fusion (residues >1000)
remove 8jsr and polymer and chain R and resi 1000-2000
remove 8jsr and (solvent or hydro)
hide everything, 8jsr
show cartoon, 8jsr and chain R
color grey85, 8jsr and chain R
set cartoon_color, grey85, 8jsr
show sticks, 8jsr and resn UYI
color yellow, 8jsr and resn UYI and elem C

select 8jsr_hel_TM3, 8jsr and chain R and resi 130 and name CA
label 8jsr_hel_TM3, "TM3"
set label_color, grey30, 8jsr_hel_TM3
set label_size, 20, 8jsr_hel_TM3
set label_position, (48.33, -13.49, 0.00), 8jsr_hel_TM3
select 8jsr_hel_TM5, 8jsr and chain R and resi 210 and name CA
label 8jsr_hel_TM5, "TM5"
set label_color, grey30, 8jsr_hel_TM5
set label_size, 20, 8jsr_hel_TM5
set label_position, (54.64, 0.00, 0.00), 8jsr_hel_TM5
select 8jsr_hel_TM6, 8jsr and chain R and resi 281 and name CA
label 8jsr_hel_TM6, "TM6"
set label_color, grey30, 8jsr_hel_TM6
set label_size, 20, 8jsr_hel_TM6
set label_position, (33.44, 0.00, 0.00), 8jsr_hel_TM6
select 8jsr_hel_TM7, 8jsr and chain R and resi 310 and name CA
label 8jsr_hel_TM7, "TM7"
set label_color, grey30, 8jsr_hel_TM7
set label_size, 20, 8jsr_hel_TM7
set label_position, (25.28, -13.49, 0.00), 8jsr_hel_TM7
select 8jsr_hel_ICL2, 8jsr and chain R and resi 145 and name CA
label 8jsr_hel_ICL2, "ICL2"
set label_color, grey30, 8jsr_hel_ICL2
set label_size, 20, 8jsr_hel_ICL2
set label_position, (43.02, 0.00, 0.00), 8jsr_hel_ICL2

select 8jsr_EC50_124, 8jsr and chain R and resi 124
show sticks, 8jsr_EC50_124 and sidechain
color firebrick, 8jsr_EC50_124 and elem C
show spheres, 8jsr_EC50_124 and name CA
color firebrick, 8jsr_EC50_124 and name CA
set label_position, (-31.34, -20.23, 0.00), 8jsr_EC50_124
label 8jsr_EC50_124 and name CA, "E124  3.4 A"
# E124: minimum heavy-atom distance 3.39 A
distance 8jsr_EC50_d124, 8jsr_EC50_124 and name OE1, 8jsr and resn UYI and name C10
hide labels, 8jsr_EC50_d124

select 8jsr_EC50_125, 8jsr and chain R and resi 125
show sticks, 8jsr_EC50_125 and sidechain
color firebrick, 8jsr_EC50_125 and elem C
show spheres, 8jsr_EC50_125 and name CA
color firebrick, 8jsr_EC50_125 and name CA
set label_position, (-26.93, -33.72, 0.00), 8jsr_EC50_125
label 8jsr_EC50_125 and name CA, "S125  6.9 A"
# S125: minimum heavy-atom distance 6.92 A
distance 8jsr_EC50_d125, 8jsr_EC50_125 and name N, 8jsr and resn UYI and name C03
hide labels, 8jsr_EC50_d125

select 8jsr_EC50_122, 8jsr and chain R and resi 122
show sticks, 8jsr_EC50_122 and sidechain
color firebrick, 8jsr_EC50_122 and elem C
show spheres, 8jsr_EC50_122 and name CA
color firebrick, 8jsr_EC50_122 and name CA
set label_position, (-27.39, -6.74, 0.00), 8jsr_EC50_122
label 8jsr_EC50_122 and name CA, "V122  6.9 A"
# V122: minimum heavy-atom distance 6.92 A
distance 8jsr_EC50_d122, 8jsr_EC50_122 and name C, 8jsr and resn UYI and name N40
hide labels, 8jsr_EC50_d122

select 8jsr_EC50_200, 8jsr and chain R and resi 200
show sticks, 8jsr_EC50_200 and sidechain
color firebrick, 8jsr_EC50_200 and elem C
show spheres, 8jsr_EC50_200 and name CA
color firebrick, 8jsr_EC50_200 and name CA
set label_position, (-31.90, -13.49, 0.00), 8jsr_EC50_200
label 8jsr_EC50_200 and name CA, "P200  4.7 A"
# P200: minimum heavy-atom distance 4.75 A
distance 8jsr_EC50_d200, 8jsr_EC50_200 and name CG, 8jsr and resn UYI and name C08
hide labels, 8jsr_EC50_d200

select 8jsr_EC50_198, 8jsr and chain R and resi 198
show sticks, 8jsr_EC50_198 and sidechain
color firebrick, 8jsr_EC50_198 and elem C
show spheres, 8jsr_EC50_198 and name CA
color firebrick, 8jsr_EC50_198 and name CA
set label_position, (-34.84, 0.00, 0.00), 8jsr_EC50_198
label 8jsr_EC50_198 and name CA, "C198  5.6 A"
# C198: minimum heavy-atom distance 5.56 A
distance 8jsr_EC50_d198, 8jsr_EC50_198 and name O, 8jsr and resn UYI and name O34
hide labels, 8jsr_EC50_d198

group 8jsr_EC50, 8jsr_EC50_124 8jsr_EC50_125 8jsr_EC50_122 8jsr_EC50_200 8jsr_EC50_198 8jsr_EC50_d*

select 8jsr_IC50_287, 8jsr and chain R and resi 287
show sticks, 8jsr_IC50_287 and sidechain
color marine, 8jsr_IC50_287 and elem C
show spheres, 8jsr_IC50_287 and name CA
color marine, 8jsr_IC50_287 and name CA
set label_position, (-40.96, 0.00, 0.00), 8jsr_IC50_287
label 8jsr_IC50_287 and name CA, "S287  5.5 A"
# S287: minimum heavy-atom distance 5.53 A
distance 8jsr_IC50_d287, 8jsr_IC50_287 and name CB, 8jsr and resn UYI and name C15
hide labels, 8jsr_IC50_d287

select 8jsr_IC50_286, 8jsr and chain R and resi 286
show sticks, 8jsr_IC50_286 and sidechain
color marine, 8jsr_IC50_286 and elem C
show spheres, 8jsr_IC50_286 and name CA
color marine, 8jsr_IC50_286 and name CA
set label_position, (-46.39, -13.49, 0.00), 8jsr_IC50_286
label 8jsr_IC50_286 and name CA, "F286  3.5 A"
# F286: minimum heavy-atom distance 3.52 A
distance 8jsr_IC50_d286, 8jsr_IC50_286 and name CD1, 8jsr and resn UYI and name C39
hide labels, 8jsr_IC50_d286

select 8jsr_IC50_278, 8jsr and chain R and resi 278
show sticks, 8jsr_IC50_278 and sidechain
color marine, 8jsr_IC50_278 and elem C
show spheres, 8jsr_IC50_278 and name CA
color marine, 8jsr_IC50_278 and name CA
set label_position, (-55.44, -26.98, 0.00), 8jsr_IC50_278
label 8jsr_IC50_278 and name CA, "P278  8.8 A"
# P278: minimum heavy-atom distance 8.79 A
distance 8jsr_IC50_d278, 8jsr_IC50_278 and name O, 8jsr and resn UYI and name C22
hide labels, 8jsr_IC50_d278

select 8jsr_IC50_116, 8jsr and chain R and resi 116
show sticks, 8jsr_IC50_116 and sidechain
color marine, 8jsr_IC50_116 and elem C
show spheres, 8jsr_IC50_116 and name CA
color marine, 8jsr_IC50_116 and name CA
set label_position, (-27.97, -26.98, 0.00), 8jsr_IC50_116
label 8jsr_IC50_116 and name CA, "C116  7.8 A"
# C116: minimum heavy-atom distance 7.84 A
distance 8jsr_IC50_d116, 8jsr_IC50_116 and name O, 8jsr and resn UYI and name N40
hide labels, 8jsr_IC50_d116

select 8jsr_IC50_147, 8jsr and chain R and resi 147
show sticks, 8jsr_IC50_147 and sidechain
color marine, 8jsr_IC50_147 and elem C
show spheres, 8jsr_IC50_147 and name CA
color marine, 8jsr_IC50_147 and name CA
set label_position, (-33.87, 0.00, 0.00), 8jsr_IC50_147
label 8jsr_IC50_147 and name CA, "F147  35.0 A"

group 8jsr_IC50, 8jsr_IC50_287 8jsr_IC50_286 8jsr_IC50_278 8jsr_IC50_116 8jsr_IC50_147 8jsr_IC50_d*

# ---------------- 6ko5: antagonist-bound ----------------
# expects 6ko5.pdb beside this script, otherwise use:
#   fetch 6KO5, 6ko5, async=0
load 6ko5.pdb, 6ko5
remove 6ko5 and not (chain A or resn 8QX)
# chain A of 6KO5 also carries a BRIL fusion (residues >1000)
remove 6ko5 and polymer and chain A and resi 1000-2000
remove 6ko5 and (solvent or hydro)
hide everything, 6ko5
show cartoon, 6ko5 and chain A
color grey85, 6ko5 and chain A
set cartoon_color, grey85, 6ko5
show sticks, 6ko5 and resn 8QX
color yellow, 6ko5 and resn 8QX and elem C

select 6ko5_hel_TM3, 6ko5 and chain A and resi 130 and name CA
label 6ko5_hel_TM3, "TM3"
set label_color, grey30, 6ko5_hel_TM3
set label_size, 20, 6ko5_hel_TM3
set label_position, (50.56, -12.71, 0.00), 6ko5_hel_TM3
select 6ko5_hel_TM5, 6ko5 and chain A and resi 210 and name CA
label 6ko5_hel_TM5, "TM5"
set label_color, grey30, 6ko5_hel_TM5
set label_size, 20, 6ko5_hel_TM5
set label_position, (60.10, 0.00, 0.00), 6ko5_hel_TM5
select 6ko5_hel_TM6, 6ko5 and chain A and resi 281 and name CA
label 6ko5_hel_TM6, "TM6"
set label_color, grey30, 6ko5_hel_TM6
set label_size, 20, 6ko5_hel_TM6
set label_position, (41.36, 0.00, 0.00), 6ko5_hel_TM6
select 6ko5_hel_TM7, 6ko5 and chain A and resi 310 and name CA
label 6ko5_hel_TM7, "TM7"
set label_color, grey30, 6ko5_hel_TM7
set label_size, 20, 6ko5_hel_TM7
set label_position, (26.72, -12.71, 0.00), 6ko5_hel_TM7
select 6ko5_hel_ICL2, 6ko5 and chain A and resi 145 and name CA
label 6ko5_hel_ICL2, "ICL2"
set label_color, grey30, 6ko5_hel_ICL2
set label_size, 20, 6ko5_hel_ICL2
set label_position, (55.11, 0.00, 0.00), 6ko5_hel_ICL2

select 6ko5_EC50_124, 6ko5 and chain A and resi 124
show sticks, 6ko5_EC50_124 and sidechain
color firebrick, 6ko5_EC50_124 and elem C
show spheres, 6ko5_EC50_124 and name CA
color firebrick, 6ko5_EC50_124 and name CA
set label_position, (-36.72, -19.06, 0.00), 6ko5_EC50_124
label 6ko5_EC50_124 and name CA, "E124  3.4 A"
# E124: minimum heavy-atom distance 3.36 A
distance 6ko5_EC50_d124, 6ko5_EC50_124 and name OE2, 6ko5 and resn 8QX and name BR1
hide labels, 6ko5_EC50_d124

select 6ko5_EC50_125, 6ko5 and chain A and resi 125
show sticks, 6ko5_EC50_125 and sidechain
color firebrick, 6ko5_EC50_125 and elem C
show spheres, 6ko5_EC50_125 and name CA
color firebrick, 6ko5_EC50_125 and name CA
set label_position, (-32.91, -31.77, 0.00), 6ko5_EC50_125
label 6ko5_EC50_125 and name CA, "S125  8.0 A"
# S125: minimum heavy-atom distance 8.03 A
distance 6ko5_EC50_d125, 6ko5_EC50_125 and name N, 6ko5 and resn 8QX and name C29
hide labels, 6ko5_EC50_d125

select 6ko5_EC50_122, 6ko5 and chain A and resi 122
show sticks, 6ko5_EC50_122 and sidechain
color firebrick, 6ko5_EC50_122 and elem C
show spheres, 6ko5_EC50_122 and name CA
color firebrick, 6ko5_EC50_122 and name CA
set label_position, (-35.96, -6.35, 0.00), 6ko5_EC50_122
label 6ko5_EC50_122 and name CA, "V122  7.7 A"
# V122: minimum heavy-atom distance 7.70 A
distance 6ko5_EC50_d122, 6ko5_EC50_122 and name C, 6ko5 and resn 8QX and name C30
hide labels, 6ko5_EC50_d122

select 6ko5_EC50_200, 6ko5 and chain A and resi 200
show sticks, 6ko5_EC50_200 and sidechain
color firebrick, 6ko5_EC50_200 and elem C
show spheres, 6ko5_EC50_200 and name CA
color firebrick, 6ko5_EC50_200 and name CA
set label_position, (-34.73, -12.71, 0.00), 6ko5_EC50_200
label 6ko5_EC50_200 and name CA, "P200  3.8 A"
# P200: minimum heavy-atom distance 3.82 A
distance 6ko5_EC50_d200, 6ko5_EC50_200 and name CD, 6ko5 and resn 8QX and name O08
hide labels, 6ko5_EC50_d200

select 6ko5_EC50_198, 6ko5 and chain A and resi 198
show sticks, 6ko5_EC50_198 and sidechain
color firebrick, 6ko5_EC50_198 and elem C
show spheres, 6ko5_EC50_198 and name CA
color firebrick, 6ko5_EC50_198 and name CA
set label_position, (-42.11, 0.00, 0.00), 6ko5_EC50_198
label 6ko5_EC50_198 and name CA, "C198  4.5 A"
# C198: minimum heavy-atom distance 4.54 A
distance 6ko5_EC50_d198, 6ko5_EC50_198 and name O, 6ko5 and resn 8QX and name C06
hide labels, 6ko5_EC50_d198

group 6ko5_EC50, 6ko5_EC50_124 6ko5_EC50_125 6ko5_EC50_122 6ko5_EC50_200 6ko5_EC50_198 6ko5_EC50_d*

select 6ko5_IC50_287, 6ko5 and chain A and resi 287
show sticks, 6ko5_IC50_287 and sidechain
color marine, 6ko5_IC50_287 and elem C
show spheres, 6ko5_IC50_287 and name CA
color marine, 6ko5_IC50_287 and name CA
set label_position, (-38.61, -19.06, 0.00), 6ko5_IC50_287
label 6ko5_IC50_287 and name CA, "S287  6.0 A"
# S287: minimum heavy-atom distance 5.97 A
distance 6ko5_IC50_d287, 6ko5_IC50_287 and name N, 6ko5 and resn 8QX and name F16
hide labels, 6ko5_IC50_d287

select 6ko5_IC50_286, 6ko5 and chain A and resi 286
show sticks, 6ko5_IC50_286 and sidechain
color marine, 6ko5_IC50_286 and elem C
show spheres, 6ko5_IC50_286 and name CA
color marine, 6ko5_IC50_286 and name CA
set label_position, (-44.76, -6.35, 0.00), 6ko5_IC50_286
label 6ko5_IC50_286 and name CA, "F286  3.3 A"
# F286: minimum heavy-atom distance 3.32 A
distance 6ko5_IC50_d286, 6ko5_IC50_286 and name CE2, 6ko5 and resn 8QX and name F16
hide labels, 6ko5_IC50_d286

select 6ko5_IC50_278, 6ko5 and chain A and resi 278
show sticks, 6ko5_IC50_278 and sidechain
color marine, 6ko5_IC50_278 and elem C
show spheres, 6ko5_IC50_278 and name CA
color marine, 6ko5_IC50_278 and name CA
set label_position, (-54.32, -19.06, 0.00), 6ko5_IC50_278
label 6ko5_IC50_278 and name CA, "P278  8.1 A"
# P278: minimum heavy-atom distance 8.09 A
distance 6ko5_IC50_d278, 6ko5_IC50_278 and name O, 6ko5 and resn 8QX and name C22
hide labels, 6ko5_IC50_d278

select 6ko5_IC50_116, 6ko5 and chain A and resi 116
show sticks, 6ko5_IC50_116 and sidechain
color marine, 6ko5_IC50_116 and elem C
show spheres, 6ko5_IC50_116 and name CA
color marine, 6ko5_IC50_116 and name CA
set label_position, (-39.00, 0.00, 0.00), 6ko5_IC50_116
label 6ko5_IC50_116 and name CA, "C116  7.4 A"
# C116: minimum heavy-atom distance 7.40 A
distance 6ko5_IC50_d116, 6ko5_IC50_116 and name O, 6ko5 and resn 8QX and name C10
hide labels, 6ko5_IC50_d116

select 6ko5_IC50_147, 6ko5 and chain A and resi 147
show sticks, 6ko5_IC50_147 and sidechain
color marine, 6ko5_IC50_147 and elem C
show spheres, 6ko5_IC50_147 and name CA
color marine, 6ko5_IC50_147 and name CA
set label_position, (-25.26, 0.00, 0.00), 6ko5_IC50_147
label 6ko5_IC50_147 and name CA, "F147  34.4 A"

group 6ko5_IC50, 6ko5_IC50_287 6ko5_IC50_286 6ko5_IC50_278 6ko5_IC50_116 6ko5_IC50_147 6ko5_IC50_d*

deselect
print 'Fig. 6 scene ready: run Fig6_preview.pml or Fig6_render_final.pml'
