SOLVER:
  BATCH_SIZE: 32
  MAX_EPOCH: 50
  LR: 1e-5
  SEED: 50
  PRETRAINED_MODEL: "result/DrugBAN_BiLSTM/best_model_epoch_94.pth"

DA:
  TASK: False
  USE: False

PROTEIN:
  USE_BILSTM: True
  LSTM_HIDDEN_DIM: 256
  LSTM_NUM_LAYERS: 2
  LSTM_DROPOUT: 0.2
  EMBEDDING_DIM: 128
  FEATURE_DIM: 4
  MAX_PROTEIN_LENGTH: 1200
  PADDING: True

DRUG:
  USE_BILSTM: False
  NODE_IN_FEATS: 75
  PADDING: True
  HIDDEN_LAYERS: [128, 128, 128]
  NODE_IN_EMBEDDING: 128
  MAX_NODES: 290

DECODER:
  BINARY: 1

BCN:
  HEADS: 2

RESULT:
  OUTPUT_DIR: "./result/DrugBAN_BiLSTM_GHSR_Seed50"
  SAVE_MODEL: True

COMET:
  PROJECT_NAME: "DrugBAN_BiLSTM_GHSR_Stability"
  TAG: "Seed_50"
