SOLVER:
  BATCH_SIZE: 32
  MAX_EPOCH: 100
  LR: 1e-4
  DA_LR: 5e-5
  SEED: 42

DA:
  TASK: True
  USE: True
  METHOD: "MMD"  # Maximum Mean Discrepancy
  USE_ENTROPY: False
  RANDOM_LAYER: False
  ORIGINAL_RANDOM: False
  RANDOM_DIM: 256
  INIT_EPOCH: 10
  LAMB_DA: 1  # MMD loss weight

DECODER:
  BINARY: 2

RESULT:
  OUTPUT_DIR: "./result/DrugBAN_MMD"
  SAVE_MODEL: True

COMET:
  PROJECT_NAME: "DrugBAN_MMD"
  TAG: "GCN_CNN_MMD"
